# Generated by Django 3.1.4 on 2021-12-16 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Stock_Influence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_price', models.IntegerField()),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='premierhoodv2.player')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='premierhoodv2.user')),
            ],
        ),
        migrations.CreateModel(
            name='Stock_Impact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_price', models.IntegerField()),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='premierhoodv2.player')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='premierhoodv2.user')),
            ],
        ),
        migrations.CreateModel(
            name='Stock_Creativity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_price', models.IntegerField()),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='premierhoodv2.player')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='premierhoodv2.user')),
            ],
        ),
    ]
