# Generated by Django 3.1.4 on 2021-12-18 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premierhoodv2', 'sql'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
