# Generated by Django 3.1.4 on 2021-12-18 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('premierhoodv2', 'storedProc5'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='buyCount',
            new_name='buy_count',
        ),
    ]
