# Generated by Django 3.1.4 on 2021-12-17 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('premierhoodv2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock_creativity',
            name='user',
        ),
        migrations.RemoveField(
            model_name='stock_impact',
            name='user',
        ),
        migrations.RemoveField(
            model_name='stock_influence',
            name='user',
        ),
    ]
