# Generated by Django 3.1.4 on 2021-12-18 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('premierhoodv2', '0001_player_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='likes',
            new_name='buyCount',
        ),
    ]
