# Generated by Django 3.1.4 on 2021-12-17 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('premierhoodv2', '0002_auto_20211217_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_creativity',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='premierhoodv2.player'),
        ),
        migrations.AlterField(
            model_name='stock_impact',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='premierhoodv2.player'),
        ),
        migrations.AlterField(
            model_name='stock_influence',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='premierhoodv2.player'),
        ),
        migrations.CreateModel(
            name='UserStocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stocks', models.ManyToManyField(to='premierhoodv2.Player')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='premierhoodv2.user')),
            ],
        ),
    ]
