# Generated by Django 3.1.4 on 2021-12-17 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('premierhoodv2', '0003_auto_20211217_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock_creativity',
            name='id',
        ),
        migrations.RemoveField(
            model_name='stock_impact',
            name='id',
        ),
        migrations.RemoveField(
            model_name='stock_influence',
            name='id',
        ),
        migrations.AlterField(
            model_name='stock_creativity',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='premierhoodv2.player'),
        ),
        migrations.AlterField(
            model_name='stock_impact',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='premierhoodv2.player'),
        ),
        migrations.AlterField(
            model_name='stock_influence',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='premierhoodv2.player'),
        ),
    ]
