# Generated by Django 3.1.4 on 2021-12-17 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premierhoodv2', '0004_auto_20211217_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_impact',
            name='current_price',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='stock_influence',
            name='current_price',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
    ]
