# Generated by Django 3.1.4 on 2021-12-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premierhoodv2', '0005_auto_20211217_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=256, primary_key=True, serialize=False),
        ),
    ]
