# Generated by Django 3.1.4 on 2021-12-17 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('premierhoodv2', '0006_auto_20211217_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstocks',
            name='id',
        ),
        migrations.AlterField(
            model_name='userstocks',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='premierhoodv2.user'),
        ),
    ]
