# Generated by Django 3.1.4 on 2021-12-18 00:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('premierhoodv2', '0007_auto_20211217_0043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstocks',
            name='stocks',
        ),
        migrations.AlterField(
            model_name='userstocks',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='premierhoodv2.user'),
        ),
    ]
