# Generated by Django 3.1.4 on 2021-12-18 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('premierhoodv2', '0008_auto_20211217_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStocksOwned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='premierhoodv2.player')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='premierhoodv2.user')),
            ],
        ),
        migrations.DeleteModel(
            name='UserStocks',
        ),
    ]
